// Quantum Caverns — a quantum maze game, and a tutorial for calling the Moth
// platform from a coccoon game.
//
// Web port of games/quantum_caverns/quantum_caverns.gd. Navigate from the red
// start to the blue exit within the step limit; your previous route stays
// visible as a dim trail. The maze itself is generated by quantum blur: a
// height map is scattered with random peaks, then blurred by rotating each
// qubit on the Bloch sphere. Cells above 0.5 become walls; the rest paths.
//
// The blur is computed by the Moth platform's blur-core-v1 engine when an API
// key is available (see the "── API" methods), falling back to the local
// QuantumBlur simulator otherwise. Callers of _genHeight never know which ran.
//
// The original uses fire-and-forget GDScript coroutines guarded by flags; this
// port uses async methods guarded by the same flags, checked each frame in
// process(). JS is single-threaded, so the flags stay consistent.

import { Coccoon, ImageList, Sprite, Text, color, Colors, type Game } from "@/lib/coccoon"
import { QuantumBlur, posKey, type HeightMap } from "@/lib/quantumblur"

const VIEW_W = 32
const VIEW_H = 17
const L = 32

const IMG_PATH = 0
const IMG_WALL = 1
const IMG_END = 2
const IMG_PLAYER = 3
const IMG_OUTSIDE = 4
const IMG_PATH_DIM = 5

type Vec = { x: number; y: number }
const DIRS: Vec[] = [
  { x: 1, y: 0 },
  { x: -1, y: 0 },
  { x: 0, y: 1 },
  { x: 0, y: -1 },
]

export class QuantumCaverns implements Game {
  private _engine!: Coccoon
  private _getApiKey: () => string
  private _onStatus?: (via: "moth" | "local" | "pending") => void

  private _tiles: Record<string, Sprite> = {}
  private _statusText!: Text
  private _titleText!: Text
  private _loadingText!: Text

  private _maze: Record<string, number> = {}
  private _start: Vec = { x: 0, y: 0 }
  private _end: Vec = { x: 0, y: 0 }
  private _maxSteps = 0
  private _player: Vec = { x: 0, y: 0 }
  private _step = 0
  private _path: Vec[] = []
  private _lastpath: Vec[] = []
  private _success = false
  private _prevKeys: number[] = []

  private _generating = false
  private _animTick = 0
  private _prefetching = false
  private _nextMazeHeight: HeightMap = {}
  private _nextMazeReady = false
  private _waitingForNext = false

  constructor(getApiKey: () => string, onStatus?: (via: "moth" | "local" | "pending") => void) {
    this._getApiKey = getApiKey
    this._onStatus = onStatus
  }

  ready(engine: Coccoon): void {
    this._engine = engine

    new ImageList(engine, [
      color(0.15, 0.5, 0.15), // 0 path
      color(0.6, 0.3, 0.0), // 1 wall
      color(0.1, 0.25, 0.9), // 2 exit
      color(0.9, 0.1, 0.1), // 3 player
      color(0.15, 0.15, 0.15), // 4 outside maze
      color(0.05, 0.22, 0.05), // 5 path dim (last loop trail)
    ])

    for (let dx = 0; dx < VIEW_W; dx++) {
      for (let sy = 0; sy < VIEW_H; sy++) {
        this._tiles[posKey(dx, sy)] = new Sprite(engine, IMG_OUTSIDE, dx, VIEW_H - sy, 0)
      }
    }

    this._statusText = new Text(
      engine,
      "Generating quantum maze",
      VIEW_W,
      2,
      0,
      0,
      28,
      Colors.WHITE,
      color(0.05, 0.05, 0.15),
    )

    this._setupTitleTiles()

    this._titleText = new Text(
      engine,
      "QUANTUM CAVERNS",
      26.0,
      3.0,
      3.0,
      12.5,
      40,
      Colors.WHITE,
      color(0.03, 0.05, 0.08, 0.88),
    )
    this._loadingText = new Text(
      engine,
      "Navigate from start (red) to exit (blue)\nwithin the step limit.\n\n" +
        "Your previous route stays visible as a trail.\n\n" +
        "Arrow keys to move\n" +
        "Space for a new maze\n" +
        "Esc to menu",
      26.0,
      6.5,
      3.0,
      5.0,
      15,
      color(0.75, 0.8, 1.0),
      color(0.03, 0.05, 0.08, 0.88),
    )

    void this._startGeneration()
  }

  // ── Generation dispatcher ──────────────────────────────────────────────────

  private async _startGeneration(): Promise<void> {
    this._generating = true
    this._animTick = 0
    this._statusText.text = "Generating quantum maze"
    const height = await this._genHeight(this._getApiKey())
    this._buildMaze(height)
    this._generating = false
    for (const t of [this._titleText, this._loadingText]) {
      t.set_font_color(color(0, 0, 0, 0))
      t.set_background_color(color(0, 0, 0, 0))
    }
    this._resetLoop()
    void this._prefetchNext()
  }

  private async _prefetchNext(): Promise<void> {
    if (this._prefetching || this._nextMazeReady) return
    this._prefetching = true
    this._nextMazeHeight = await this._genHeight(this._getApiKey())
    this._nextMazeReady = true
    this._prefetching = false
  }

  private _applyNextMaze(): void {
    this._buildMaze(this._nextMazeHeight)
    this._nextMazeHeight = {}
    this._nextMazeReady = false
    this._waitingForNext = false
    this._resetLoop()
    void this._prefetchNext()
  }

  // ── Title screen tiles ──────────────────────────────────────────────────────
  //
  // A seeded pattern plus one cellular-automaton pass clusters walls into
  // organic blobs while the first maze generates, so the loading screen looks
  // like a piece of the world rather than a blank slate.

  private _setupTitleTiles(): void {
    let seed = 42
    const rand = () => {
      // deterministic LCG so the title looks identical every load
      seed = (seed * 1103515245 + 12345) & 0x7fffffff
      return seed / 0x7fffffff
    }
    const raw: boolean[][] = []
    for (let dx = 0; dx < VIEW_W; dx++) {
      const col: boolean[] = []
      for (let sy = 0; sy < VIEW_H; sy++) col.push(rand() < 0.46)
      raw.push(col)
    }
    for (let dx = 0; dx < VIEW_W; dx++) {
      for (let sy = 0; sy < VIEW_H; sy++) {
        const key = posKey(dx, sy)
        if (dx === 0 || dx === VIEW_W - 1 || sy === 0 || sy === VIEW_H - 1) {
          this._tiles[key].image_id = IMG_WALL
          continue
        }
        let walls = 0
        for (const d of DIRS) {
          const nx = dx + d.x
          const ny = sy + d.y
          if (nx < 0 || nx >= VIEW_W || ny < 0 || ny >= VIEW_H) walls += 1
          else if (raw[nx][ny]) walls += 1
        }
        this._tiles[key].image_id = walls >= 2 ? IMG_WALL : IMG_PATH
      }
    }
    this._tiles[posKey(3, 3)].image_id = IMG_PLAYER
    this._tiles[posKey(28, 13)].image_id = IMG_END
  }

  // ── Height generation ────────────────────────────────────────────────────────
  //
  // Single entry point for both paths: try the Moth platform first when a key
  // is set, fall back to the local QuantumBlur simulator otherwise.

  private async _genHeight(key: string): Promise<HeightMap> {
    if (key.length > 0) {
      const h = await this._genHeightApi(key)
      if (h && Object.keys(h).length > 0) {
        this._onStatus?.("moth")
        return h
      }
    }
    this._onStatus?.("local")
    return this._genHeightLocal()
  }

  private _makeInitialHeight(): HeightMap {
    const height: HeightMap = {}
    for (let x = 0; x < L; x++) {
      for (let y = 0; y < L; y++) height[posKey(x, y)] = 0.0
    }
    for (let i = 0; i < L; i++) {
      height[posKey(Math.floor(Math.random() * L), Math.floor(Math.random() * L))] = Math.random()
    }
    return height
  }

  // ── API: blur via the Moth platform ─────────────────────────────────────────
  //
  // The server route owns the async job model (submit -> poll -> download);
  // here we just hand it the initial grid and the caller's key, then decode the
  // blurred grid it returns. Any failure resolves to null so _genHeight falls
  // through to the local path.

  private async _genHeightApi(key: string): Promise<HeightMap | null> {
    const height = this._makeInitialHeight()
    try {
      const res = await fetch("/api/moth-blur", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ values: this._heightToArray(height), strength: 0.25, key }),
      })
      if (!res.ok) return null
      const data = (await res.json()) as { result?: unknown }
      return this._extractHeight(data.result)
    } catch {
      return null
    }
  }

  // ── Array <-> height map conversion ─────────────────────────────────────────

  private _heightToArray(height: HeightMap): number[][] {
    const arr: number[][] = []
    for (let y = 0; y < L; y++) {
      const row: number[] = []
      for (let x = 0; x < L; x++) row.push(height[posKey(x, y)])
      arr.push(row)
    }
    return arr
  }

  private _extractHeight(data: unknown): HeightMap | null {
    let arr: unknown = null
    if (Array.isArray(data)) {
      arr = data
    } else if (data && typeof data === "object") {
      const obj = data as Record<string, unknown>
      arr = obj.values ?? obj.result ?? null
    }
    if (!Array.isArray(arr) || arr.length === 0) return null
    const height: HeightMap = {}
    const rows = Math.min(L, arr.length)
    for (let y = 0; y < rows; y++) {
      const row = arr[y]
      if (!Array.isArray(row)) continue
      const cols = Math.min(L, row.length)
      for (let x = 0; x < cols; x++) height[posKey(x, y)] = Number(row[x])
    }
    return height
  }

  // ── Local fallback ───────────────────────────────────────────────────────────
  //
  // Same quantum blur, run in-browser: encode the height map into a circuit,
  // apply one Rx(pi/8) per qubit (strength 0.25), decode the result.

  private _genHeightLocal(): HeightMap {
    const height = this._makeInitialHeight()
    const qc = QuantumBlur.height2circuit(height, L)
    for (let j = 0; j < qc.numQubits; j++) qc.rx(Math.PI * 0.125, j)
    return QuantumBlur.circuit2height(qc, L, L, true)
  }

  // ── Maze construction from height map ────────────────────────────────────────

  private _buildMaze(newHeight: HeightMap): void {
    this._maze = {}
    for (let x = 0; x < L; x++) {
      for (let y = 0; y < L; y++) {
        const key = posKey(x, y)
        if (x === 0 || x === L - 1 || y === 0 || y === L - 1) {
          this._maze[key] = 1
        } else {
          this._maze[key] = (newHeight[key] ?? 1.0) > 0.5 ? 1 : 0
        }
      }
    }

    const pathCells: Vec[] = []
    for (let x = 0; x < L; x++) {
      for (let y = 0; y < L; y++) {
        if (this._maze[posKey(x, y)] === 0) pathCells.push({ x, y })
      }
    }

    const largest = this._largestComponent(pathCells)
    const largestSet = new Set(largest.map((p) => posKey(p.x, p.y)))
    for (const p of pathCells) {
      if (!largestSet.has(posKey(p.x, p.y))) this._maze[posKey(p.x, p.y)] = 1
    }

    const r1 = this._bfs(largest[0], largestSet)
    const r2 = this._bfs(r1.farthest, largestSet)
    const r3 = this._bfs(r2.farthest, largestSet)
    this._start = r2.farthest
    this._end = r3.farthest
    this._maxSteps = r3.dist + 2
  }

  // ── Graph helpers ────────────────────────────────────────────────────────────

  private _bfs(from: Vec, valid: Set<string>): { farthest: Vec; dist: number } {
    const dist: Record<string, number> = { [posKey(from.x, from.y)]: 0 }
    const queue: Vec[] = [from]
    let head = 0
    let farthest = from
    while (head < queue.length) {
      const pos = queue[head]
      head += 1
      for (const d of DIRS) {
        const nxt = { x: pos.x + d.x, y: pos.y + d.y }
        const nk = posKey(nxt.x, nxt.y)
        if (valid.has(nk) && !(nk in dist)) {
          dist[nk] = dist[posKey(pos.x, pos.y)] + 1
          queue.push(nxt)
          if (dist[nk] > dist[posKey(farthest.x, farthest.y)]) farthest = nxt
        }
      }
    }
    return { farthest, dist: dist[posKey(farthest.x, farthest.y)] }
  }

  private _largestComponent(cells: Vec[]): Vec[] {
    const unvisited = new Set(cells.map((p) => posKey(p.x, p.y)))
    let largest: Vec[] = []
    while (unvisited.size > 0) {
      const startKey = unvisited.values().next().value as string
      const [sx, sy] = startKey.split(",").map(Number)
      const start = { x: sx, y: sy }
      const visited: Vec[] = []
      const queue: Vec[] = [start]
      const inQ = new Set<string>([startKey])
      let head = 0
      while (head < queue.length) {
        const pos = queue[head]
        head += 1
        visited.push(pos)
        unvisited.delete(posKey(pos.x, pos.y))
        for (const d of DIRS) {
          const nxt = { x: pos.x + d.x, y: pos.y + d.y }
          const nk = posKey(nxt.x, nxt.y)
          if (unvisited.has(nk) && !inQ.has(nk)) {
            inQ.add(nk)
            queue.push(nxt)
          }
        }
      }
      if (visited.length > largest.length) largest = visited
    }
    return largest
  }

  // ── Game loop ────────────────────────────────────────────────────────────────

  private _resetLoop(): void {
    this._player = this._start
    this._step = 0
    this._path = [this._start]
    this._success = false
    this._render()
  }

  private _scrollY(): number {
    return Math.max(0, Math.min(this._player.y - Math.floor(VIEW_H / 2), L - VIEW_H))
  }

  private _tileImg(pos: Vec, inLast: boolean): number {
    const key = posKey(pos.x, pos.y)
    if (!(key in this._maze)) return IMG_OUTSIDE
    if (pos.x === this._player.x && pos.y === this._player.y) return IMG_PLAYER
    if (pos.x === this._end.x && pos.y === this._end.y) return IMG_END
    if (this._maze[key] === 1) return IMG_WALL
    return inLast ? IMG_PATH_DIM : IMG_PATH
  }

  private _render(): void {
    const sy = this._scrollY()
    const lpSet = new Set(this._lastpath.map((p) => posKey(p.x, p.y)))
    for (let dx = 0; dx < VIEW_W; dx++) {
      for (let screenY = 0; screenY < VIEW_H; screenY++) {
        const mazePos = { x: dx, y: sy + screenY }
        this._tiles[posKey(dx, screenY)].image_id = this._tileImg(mazePos, lpSet.has(posKey(mazePos.x, mazePos.y)))
      }
    }
    if (this._success) {
      this._statusText.text = "You made it out! Space = new maze."
    } else {
      this._statusText.text = `${this._maxSteps - this._step} steps to reach the exit.`
    }
  }

  process(_delta: number, engine: Coccoon): void {
    if (this._generating) {
      this._animTick += 1
      if (this._animTick % 10 === 0) {
        this._statusText.text = "Generating quantum maze" + ".".repeat(Math.floor(this._animTick / 10) % 4)
      }
      return
    }

    if (this._waitingForNext) {
      this._animTick += 1
      if (this._animTick % 10 === 0) {
        this._statusText.text = "Generating quantum maze" + ".".repeat(Math.floor(this._animTick / 10) % 4)
      }
      if (this._nextMazeReady) this._applyNextMaze()
      return
    }

    const inp = engine.update()
    const keys = inp.key_presses
    const justPressed: number[] = []
    for (const k of keys) if (!this._prevKeys.includes(k)) justPressed.push(k)
    this._prevKeys = keys.slice()

    if (this._success) {
      if (justPressed.includes(4)) {
        this._lastpath = []
        if (this._nextMazeReady) {
          this._applyNextMaze()
        } else {
          this._waitingForNext = true
          this._animTick = 0
          this._statusText.text = "Generating quantum maze"
        }
      }
      return
    }

    if (this._step >= this._maxSteps) {
      this._lastpath = this._path.slice()
      this._resetLoop()
      return
    }

    // One axis per step, priority order, so a frame that happens to carry two
    // keys can never force a blocked diagonal move.
    let dx = 0
    let dy = 0
    if (justPressed.includes(0)) dy = -1
    else if (justPressed.includes(2)) dy = 1
    else if (justPressed.includes(3)) dx = -1
    else if (justPressed.includes(1)) dx = 1

    if (dx !== 0 || dy !== 0) {
      const nxt = { x: this._player.x + dx, y: this._player.y + dy }
      if ((this._maze[posKey(nxt.x, nxt.y)] ?? 1) === 0) {
        this._player = nxt
        this._step += 1
        this._path.push(nxt)
        if (this._player.x === this._end.x && this._player.y === this._end.y) this._success = true
      }
      this._render()
    }
  }
}
